### ISSUE TITLE
亲 有 api.umeng.com的开发文档么 

### ISSUE THREAD

**Issue by xianhuawei** [guizijiang/Umengopenapi#1]
网上找不到
查了下要企业认证用户才有
能给个完整的api文档么？
有的话 给我一份 xianhuawei.zhcn@qq.com 谢谢

**Comment by wilsonssss** [comment]
https://developer.umeng.com/open-api/apply?spm=a311a.9588098.0.0
https://developer.umeng.com/docs/67641/detail/68566
https://download.csdn.net/download/itbossbaby/9247249
